SemVer.parse()

SemVer.validate()

SemVer.compare()

SemVer.sort()

SemVer.incrementMajor()

SemVer.incrementMinor()

SemVer.incrementPatch()

SemVer.parseConstraint()

SemVer.satisfies()

SemVer.resolve()
